#!/usr/bin/python3
from numpy import *
from matplotlib.pyplot import *
# rcParams['font.family'] = "serif" 
# rcParams['font.size'] = "8" 
# rcParams['text.latex.preamble'] = [r'\usepackage{times}', r'\usepackage{mathptm}'] 
# rcParams['text.usetex'] = 'true'

################################################################################
# WARNING                                                                      #
# This software is not finished yet, and some formulas are incorrect!          #
################################################################################

# Input
Z0 = 50
fL = 0.6e9
S11L = -0.074 - 0.5235j
S21L = 0.8468 - 0.01895j
S22L = 0.0538 - 0.52705j
fH = 1.6e9
S11H = -0.5065 - 0.5161j
S21H = 0.5057 - 0.4534j
S22H = -0.46843 - 0.55308j

wL = 2*pi*fL
wH = 2*pi*fH

SL = array([S11L, S21L, S22L])
SH = array([S11H, S21H, S22H])

def X1(S):
    S11,S21,S22 = S
    print(S22)
    return Z0*imag((1+S11+S22+(S11*S22-S21**2)) / (1+S22-S11-2*S21-(S11*S22-S21**2)))

def X2(S):
    S11,S21,S22 = S
    return Z0*imag((1+S11+S22+(S11*S22-S21**2)) / (1+S11-S22-2*S21-(S11*S22-S21**2)))

def Xs(S):
    S11,S21,S22 = S
    return Z0*imag(2*S21/(1+S11+S22+S11*S22-S21**2))

L1 = (wL*X1(SL) - wH*X1(SH)) / (wL**2 + wH**2)
L2 = (wL*X2(SL) - wH*X2(SH)) / (wL**2 + wH**2)
Ls = (wL*Xs(SL) - wH*Xs(SH)) / (wL**2 + wH**2)
C1 = (wL**2-wH**2)/(wL*wH) * 1 / (wH*X1(SL) - wL*X1(SH))
C2 = (wL**2-wH**2)/(wL*wH) * 1 / (wH*X2(SL) - wL*X2(SH))
Cs = (wL**2-wH**2)/(wL*wH) * 1 / (wH*Xs(SL) - wL*Xs(SH))

print("L1", L1*1e9)
print("L2", L2*1e9)
print("Ls", Ls*1e9)
print("C1", C1*1e12)
print("C2", C2*1e12)
print("Cs", Cs*1e12)
